# Generated by Django 2.0 on 2017-12-20 03:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('website', '0001_initial'), ('website', '0002_auto_20171219_0043'), ('website', '0003_auto_20171219_2223'), ('website', '0004_auto_20171220_0137'), ('website', '0005_auto_20171220_0201'), ('website', '0006_auto_20171220_0425')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('A', 'Apples'), ('B', 'Bananas'), ('C', 'Carrots'), ('D', 'Dates'), ('E', 'Eggplants')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9)])),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(4)])),
                ('load_type', models.CharField(choices=[('A', 'Apples'), ('B', 'Bananas'), ('C', 'Carrots'), ('D', 'Dates'), ('E', 'Eggplants')], default='A', max_length=15)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='productunit',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Shelf'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Transport'),
        ),
        migrations.RenameModel(
            old_name='ProductUnit',
            new_name='Load',
        ),
        migrations.RenameField(
            model_name='load',
            old_name='product_type',
            new_name='load_type',
        ),
        migrations.AlterField(
            model_name='load',
            name='load_type',
            field=models.CharField(choices=[('A', 'Apples'), ('B', 'Bananas'), ('C', 'Carrots'), ('D', 'Dates'), ('E', 'Eggplants')], default='A', max_length=15),
        ),
    ]
