# Generated by Django 2.0 on 2017-12-18 15:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('A', 'Apples'), ('B', 'Bananas'), ('C', 'Carrots'), ('D', 'Dates'), ('E', 'Eggplants')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9)])),
                ('prod1_type', models.CharField(blank=True, choices=[('A', 'Apples'), ('B', 'Bananas'), ('C', 'Carrots'), ('D', 'Dates'), ('E', 'Eggplants')], default='', max_length=15)),
                ('prod1_count', models.PositiveIntegerField(default=0)),
                ('prod2_type', models.CharField(blank=True, choices=[('A', 'Apples'), ('B', 'Bananas'), ('C', 'Carrots'), ('D', 'Dates'), ('E', 'Eggplants')], default='', max_length=15)),
                ('prod2_count', models.PositiveIntegerField(default=0)),
                ('prod3_type', models.CharField(blank=True, choices=[('A', 'Apples'), ('B', 'Bananas'), ('C', 'Carrots'), ('D', 'Dates'), ('E', 'Eggplants')], default='', max_length=15)),
                ('prod3_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(4)])),
                ('product_type', models.CharField(choices=[('A', 'Apples'), ('B', 'Bananas'), ('C', 'Carrots'), ('D', 'Dates'), ('E', 'Eggplants')], default='A', max_length=15)),
                ('load_size', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.AddField(
            model_name='productunit',
            name='shelf',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.Shelf'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='transport',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.Transport'),
        ),
    ]
