# Generated by Django 2.0 on 2017-12-22 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_squashed_0006_auto_20171220_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
    ]
