# Generated by Django 2.0 on 2017-12-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20171219_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelf',
            name='prod1_count',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='prod1_type',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='prod2_count',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='prod2_type',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='prod3_count',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='prod3_type',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='load_size',
        ),
    ]
