# Generated by Django 2.0 on 2017-12-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20171220_0137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductUnit',
            new_name='Load',
        ),
        migrations.RenameField(
            model_name='load',
            old_name='product_type',
            new_name='load_type',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='product_type',
            new_name='load_type',
        ),
    ]
