# Generated by Django 2.0 on 2017-12-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='display_name',
            field=models.CharField(default=models.CharField(max_length=15, unique=True), max_length=20, unique=True),
        ),
    ]
