# Generated by Django 2.0 on 2017-12-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20171220_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='load_type',
            field=models.CharField(choices=[('A', 'Apples'), ('B', 'Bananas'), ('C', 'Carrots'), ('D', 'Dates'), ('E', 'Eggplants')], default='A', max_length=15),
        ),
    ]
